# Generated by Django 2.2.7 on 2020-12-30 08:32

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=20, verbose_name='分类名称')),
                ('index', models.IntegerField(default=999, verbose_name='索引')),
                ('category_mark', models.CharField(default='', max_length=20, verbose_name='分类标志')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类列表',
                'verbose_name_plural': '分类列表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=70, verbose_name='客户名称')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cos_logo/%Y/%m/%d/', verbose_name='客户头像')),
                ('company', models.CharField(max_length=216, verbose_name='客户公司')),
                ('position', models.CharField(max_length=128, verbose_name='客户职位')),
                ('star', models.PositiveIntegerField(default=5, verbose_name='评论星级')),
                ('content', models.TextField(blank=True, default='', max_length=500, verbose_name='评论内容')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '客户评论表',
                'verbose_name_plural': '客户评论表',
            },
        ),
        migrations.CreateModel(
            name='OnlineMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=70, verbose_name='姓名')),
                ('phone', models.CharField(max_length=70, verbose_name='电话')),
                ('email', models.CharField(max_length=70, verbose_name='邮箱')),
                ('weichat', models.CharField(default='guo20123762', max_length=70, verbose_name='邮箱')),
                ('content', models.TextField(blank=True, default='', max_length=500, verbose_name='留言内容')),
                ('is_handle', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否处理')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '在线咨询',
                'verbose_name_plural': '在线咨询',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('excerpt', models.TextField(blank=True, default='', max_length=200, verbose_name='咨询摘要')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news_img/%Y/%m/%d/', verbose_name='新闻封面')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='新闻内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('author', models.CharField(default='知鱼定制', max_length=70, verbose_name='作者')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_category', to='shiji.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '新闻管理',
                'verbose_name_plural': '新闻管理',
            },
        ),
    ]
